<a href="https://colab.research.google.com/github/IrisMon/BeginnerMachineLearning/blob/main/Basics_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basics of Numpy**

```
Numpy is the fundamental package for scientific computing with Python. It contains among  other things:

* A powerful N-dimensional array object
* Sophisticated (broadcasting) functions
* Tools for integrating C/C++ and Fortran code
* Useful linear algebra , Fourier transform , and random number capabilities
```



In [1]:
## Importing the numpy library 
import numpy as np

In [4]:
##Check version of the numpy library
np.__version__

'1.19.5'

In [5]:
## Create a numpy array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [6]:
[1,2,'2',5,False]

[1, 2, '2', 5, False]

In [7]:
## Only create a the same type of date
np.array([1,2,'2',5,False])

array(['1', '2', '2', '5', 'False'], dtype='<U21')

In [9]:
# Create a sample list
sample_list=[1,2,3,4,5,6]
print(sample_list)

[1, 2, 3, 4, 5, 6]


In [10]:
sample_list*2 ## Just repit 2 twice the same information

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [11]:
sample_list*3

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [13]:
## Now create a sample numpy array 
sample_numpy_array=np.array([1,2,3,4,5,6])
print(sample_numpy_array)

[1 2 3 4 5 6]


In [14]:
sample_numpy_array*2

array([ 2,  4,  6,  8, 10, 12])

In [15]:
sample_numpy_array*3

array([ 3,  6,  9, 12, 15, 18])

Create a matrix using numpy

In [16]:
a=[[1,2,3],
   [4,5,6],
   [7,8,9]]

In [17]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
a=np.array(a)

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a[0][1]

2

In [21]:
b=np.array([[1,2,3],
   [4,5,6],
   [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
#Create a 3x3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[2, 3, 3],
       [5, 5, 6],
       [9, 2, 9]])

In [23]:
#Create another matrix
np.random.randint(1,1000,(5,5))

array([[ 23, 493, 181, 154, 994],
       [ 92, 782, 445, 340, 223],
       [759, 432, 996, 152,  17],
       [368, 771, 161, 271, 969],
       [141, 496, 423, 941, 908]])

We got a different matrix when we generated another random matrix: We can get the same matrix again by fixinf the seed.

In [26]:
#Fixing the random seed
np.random.seed(1)
np.random.randint(0,20,(3,3))

array([[ 5, 11, 12],
       [ 8,  9, 11],
       [ 5, 15,  0]])

In [27]:
np.random.seed(1)
np.random.randint(0,20,(3,3))

array([[ 5, 11, 12],
       [ 8,  9, 11],
       [ 5, 15,  0]])

Creae a matrix of Zeros of specific dimension 

In [30]:
# createa 2x10 integer array filled with zerops
np.zeros((2,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
# createa 4x5 integer array filled with zerops
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
#Create a 2x10 matrix of Ones of specific dimension
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
np.ones((2,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [35]:
## Creating a Identity matrix
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
np.identity(2,dtype=int)

array([[1, 0],
       [0, 1]])

Create a matrix of filled with any specific number of specific dimension

In [37]:
#Create a 3x5 array filled with 3.14
np.full((3,5),3.22)

array([[3.22, 3.22, 3.22, 3.22, 3.22],
       [3.22, 3.22, 3.22, 3.22, 3.22],
       [3.22, 3.22, 3.22, 3.22, 3.22]])

In [38]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [39]:
## Create a 2x4 array filled with 7
np.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

Array Concatenation

In [41]:
#Convatenating 2-D array
matrix1=np.array([[1,2,3],
                  [4,5,6]])
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [45]:
matrix2=np.array([[7,8,9],
                  [10,11,12]])
print(matrix2)
matrix2

[[ 7  8  9]
 [10 11 12]]


array([[ 7,  8,  9],
       [10, 11, 12]])

Concatenate Row rise

In [46]:
# Concatenate along the first axis
matrix_1_2_combineRowwise=np.concatenate([matrix1,matrix2],axis=0)
print('Combined on row (axis=0)')
matrix_1_2_combineRowwise

Combined on row (axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Concatenate Column wise

In [47]:
matrix_1_2_combineColwise=np.concatenate([matrix1,matrix2],axis=1)
print('Combined on Col (axis=1)')
matrix_1_2_combineColwise

Combined on Col (axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])